version: 2

workflows:
  version: 2
  workflow:
    jobs:
    - deploy:
        filters:
          branches:
            only: develop

jobs:
  deploy:
    docker:
    - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: gulp build
      - deploy:
          name: Deploy
          command: gulp deploy
